# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ReadingQuantified' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadingQuantified
  pod 'Alamofire', '~> 4.8.2'
  pod 'SwiftyJSON'

  target 'ReadingQuantifiedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReadingQuantifiedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
